# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f9f77674589265362f608feaaa4e716a0ad0cee3d01fbd8e16463c58e359dd8f0eb14728dd61785959747f8c7bb638533bbbcec54379166e491ec6c8f952ab4

test:
  secret_key_base: b13cea794e0d4e0f73e5c0198aade3afcd510ea1ab8316197e76583f2509a8a69829cb68a8eff7530a8c537997114ef217facc8dca69f7996cfc7c4aca681ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
